WITH
	INCOMES_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.INCOMES
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	INVESTMENT_WITHDRAWAL_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.INVESTMENT_WITHDRAWALS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	INVESTMENT_DEPOSIT_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.INVESTMENT_DEPOSITS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	EXPENSES_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.EXPENSES
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	TRANSFERS_IN AS (
		SELECT
			DESTINATION_ACCOUNT_ID AS ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.TRANSFERS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	TRANSFERS_OUT AS (
		SELECT
			SOURCE_ACCOUNT_ID AS ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.TRANSFERS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	CARD_PAYMENTS_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.CARD_PAYMENTS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	UNION_ALL_TRANSACTIONS AS (
		SELECT
			*
		FROM
			INCOMES_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			INVESTMENT_WITHDRAWAL_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			INVESTMENT_DEPOSIT_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			EXPENSES_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			TRANSFERS_IN
		UNION ALL
		SELECT
			*
		FROM
			TRANSFERS_OUT
		UNION ALL
		SELECT
			*
		FROM
			CARD_PAYMENTS_TOTAL
	),
	DATES_FILTERS AS (
		SELECT
			MIN(TIME) AS INITIAL_DATE,
			MAX(TIME) FINALY_DATE
		FROM
			UNION_ALL_TRANSACTIONS
	),
	MESES AS (
		SELECT
			GENERATE_SERIES(
				INITIAL_DATE,
				FINALY_DATE,
				'1 month'
			) MES_REF
		FROM
			DATES_FILTERS
	),
	CARTEZIANO_CONTA_MES AS (
		SELECT
			ACCOUNTS.ID AS ACCOUNT_ID,
			MES_REF,
			0 AS TOTAL
		FROM
			FINTRACK.ACCOUNTS
			CROSS JOIN MESES
	),
	CONTAS_TOTAIS AS (
		SELECT
			ACCOUNTS.ID AS ACCOUNT_ID,
			ACCOUNTS.NAME,
			ALL_TRANSACTIONS.TIME,
			SUM(SUM(ALL_TRANSACTIONS.TOTAL)) OVER (
				PARTITION BY
					ACCOUNTS.ID
				ORDER BY
					TIME
			) AS SALDO_ACUMULADO
		FROM
			(
				SELECT
					*
				FROM
					UNION_ALL_TRANSACTIONS
				UNION ALL
				SELECT
					*
				FROM
					CARTEZIANO_CONTA_MES
			) ALL_TRANSACTIONS
			INNER JOIN FINTRACK.ACCOUNTS ON ACCOUNTS.ID = ALL_TRANSACTIONS.ACCOUNT_ID
		GROUP BY
			ACCOUNTS.ID,
			ACCOUNTS.NAME,
			TIME
	)
SELECT
	CONTAS_TOTAIS.NAME,
	SUM(
		COALESCE(
			CONTAS_TOTAIS.SALDO_ACUMULADO,
			0
		)
	) SALDO_ACUMULADO
FROM
	CONTAS_TOTAIS
WHERE
	TIME = TO_DATE('${year}-${month}-01', 'YYYY-MM-DD')
GROUP BY
	CONTAS_TOTAIS.NAME
ORDER BY
	SALDO_ACUMULADO DESC