WITH
	CARD_CHARGEBACKS_INFOS AS (
		SELECT
			CARD_ID,
			BILLING_MONTH,
			TRANSACTION_DATE,
			DESCRIPTION,
			'1671a9f4-985f-4359-a464-a0c920f7ced3'::uuid AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::uuid AS SUBCATEGORY_ID,
			AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME
		FROM
			FINTRACK.CARD_CHARGEBACKS
	),
	CARD_EXPENSES_INFOS AS (
		SELECT
			CARD_ID,
			BILLING_MONTH,
			TRANSACTION_DATE,
			DESCRIPTION,
			CATEGORY_ID,
			SUBCATEGORY_ID,
			(- AMOUNT) AS AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME
		FROM
			FINTRACK.CARD_EXPENSES
	),
	UNION_ALL_TRANSACTIONS AS (
		SELECT
			*
		FROM
			CARD_EXPENSES_INFOS
		UNION ALL
		SELECT
			*
		FROM
			CARD_CHARGEBACKS_INFOS
	),
	TRANSACTION_WITH_INFOS AS (
	SELECT
		A.TIME,
		A.TRANSACTION_DATE,
		A.DESCRIPTION,
		C.NAME AS CATEGORY,
		D.NAME AS SUBCATEGORY,
		E.NAME AS CARD,
		A.BILLING_MONTH AS ANOMES,
		TO_DATE(A.BILLING_MONTH || '-01', 'YYYY-MM-DD') AS BILLING_MONTH_DATE,
		A.AMOUNT
	FROM UNION_ALL_TRANSACTIONS A
	
	LEFT JOIN FINTRACK.INVOICES B
	ON A.CARD_ID = B.CARD_ID AND A.BILLING_MONTH = B.BILLING_MONTH
	
	LEFT JOIN FINTRACK.CATEGORIES C
	ON A.CATEGORY_ID = C.ID

	LEFT JOIN FINTRACK.SUB_CATEGORIES D
	ON A.SUBCATEGORY_ID = D.ID

	LEFT JOIN FINTRACK.CARDS E
	ON B.CARD_ID = E.ID
	
	)
		SELECT
					TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD') AS TRANSACTION_DATE,
      		DESCRIPTION,
					AMOUNT,
					ANOMES,
					CARD,
      		CATEGORY,
      		SUBCATEGORY
		FROM
			TRANSACTION_WITH_INFOS
		WHERE
		ANOMES = '${year}-${month}'
		ORDER BY TRANSACTION_DATE, AMOUNT