WITH
	INCOMES_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.INCOMES
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	INVESTMENT_WITHDRAWAL_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.INVESTMENT_WITHDRAWALS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	INVESTMENT_DEPOSIT_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.INVESTMENT_DEPOSITS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	EXPENSES_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.EXPENSES
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	TRANSFERS_IN AS (
		SELECT
			DESTINATION_ACCOUNT_ID AS ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.TRANSFERS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	TRANSFERS_OUT AS (
		SELECT
			SOURCE_ACCOUNT_ID AS ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.TRANSFERS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	CARD_PAYMENTS_TOTAL AS (
		SELECT
			ACCOUNT_ID,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			- SUM(AMOUNT) AS TOTAL
		FROM
			FINTRACK.CARD_PAYMENTS
		GROUP BY
			ACCOUNT_ID,
			TIME
	),
	UNION_ALL_TRANSACTIONS AS (
		SELECT
			*
		FROM
			INCOMES_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			INVESTMENT_WITHDRAWAL_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			INVESTMENT_DEPOSIT_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			EXPENSES_TOTAL
		UNION ALL
		SELECT
			*
		FROM
			TRANSFERS_IN
		UNION ALL
		SELECT
			*
		FROM
			TRANSFERS_OUT
		UNION ALL
		SELECT
			*
		FROM
			CARD_PAYMENTS_TOTAL
	),
	DATES_FILTERS AS (
		SELECT
			MIN(TIME) AS INITIAL_DATE,
			MAX(TIME) FINALY_DATE
		FROM
			UNION_ALL_TRANSACTIONS
	),
	MESES AS (
		SELECT
			GENERATE_SERIES(INITIAL_DATE, FINALY_DATE, '1 month') MES_REF
		FROM
			DATES_FILTERS
	),
	CARTEZIANO_CONTA_MES AS (
		SELECT
			ACCOUNTS.ID AS ACCOUNT_ID,
			MES_REF,
			0 AS TOTAL
		FROM
			FINTRACK.ACCOUNTS
			CROSS JOIN MESES
	),
	CONTAS_TOTAIS AS (
		SELECT
			ACCOUNTS.ID AS ACCOUNT_ID,
			ACCOUNTS.NAME,
			ALL_TRANSACTIONS.TIME,
			SUM(SUM(ALL_TRANSACTIONS.TOTAL)) OVER (
				PARTITION BY
					ACCOUNTS.ID
				ORDER BY
					TIME
			) AS SALDO_ACUMULADO
		FROM
			(
				SELECT
					*
				FROM
					UNION_ALL_TRANSACTIONS
				UNION ALL
				SELECT
					*
				FROM
					CARTEZIANO_CONTA_MES
			) ALL_TRANSACTIONS
			INNER JOIN FINTRACK.ACCOUNTS ON ACCOUNTS.ID = ALL_TRANSACTIONS.ACCOUNT_ID
		GROUP BY
			ACCOUNTS.ID,
			ACCOUNTS.NAME,
			TIME
	),
	-- CORREÇÃO: Separar em duas CTEs para evitar o erro de GROUP BY
	SALDO_MES_ANTERIOR_BASE AS (
		SELECT
			ACCOUNT_ID,
			SALDO_ACUMULADO
		FROM
			CONTAS_TOTAIS
		WHERE
			TIME = TO_DATE('${year}-${month}-01', 'YYYY-MM-DD') - INTERVAL '1 months'
	),
	TOTAL_MES_ANTERIOR AS (
		SELECT
			ACCOUNT_ID,
			TO_DATE('${year}-${month}-01', 'YYYY-MM-DD') AS TRANSACTION_DATE,
			'Saldo mês anterior' AS DESCRIPTION,
			'00000000-0000-0000-0000-000000000000'::UUID AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::UUID AS SUBCATEGORY_ID,
			SALDO_ACUMULADO AS AMOUNT,
			DATE_TRUNC('month', TO_DATE('${year}-${month}-01', 'YYYY-MM-DD')) AS TIME,
			1 AS IS_LAST_AMOUNT
		FROM
			SALDO_MES_ANTERIOR_BASE
	),
	INCOMES_INFOS AS (
		SELECT
			ACCOUNT_ID,
			TRANSACTION_DATE,
			DESCRIPTION,
			CATEGORY_ID,
			SUBCATEGORY_ID,
			AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.INCOMES
	),
	INVESTMENT_WITHDRAWAL_INFOS AS (
		SELECT
			ACCOUNT_ID,
			TRANSACTION_DATE,
			DESCRIPTION,
			'95c8f1f9-f042-46b5-a83d-7016e37caca2'::UUID AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::UUID AS SUBCATEGORY_ID,
			AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.INVESTMENT_WITHDRAWALS
	),
	INVESTMENT_DEPOSIT_INFOS AS (
		SELECT
			ACCOUNT_ID,
			TRANSACTION_DATE,
			DESCRIPTION,
			'95c8f1f9-f042-46b5-a83d-7016e37caca2'::UUID AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::UUID AS SUBCATEGORY_ID,
			- AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.INVESTMENT_DEPOSITS
	),
	EXPENSES_INFOS AS (
		SELECT
			ACCOUNT_ID,
			TRANSACTION_DATE,
			DESCRIPTION,
			CATEGORY_ID,
			SUBCATEGORY_ID,
			- AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.EXPENSES
	),
	TRANSFERS_IN_INFOS AS (
		SELECT
			DESTINATION_ACCOUNT_ID AS ACCOUNT_ID,
			TRANSACTION_DATE,
			'TRANSFERENCIA ENTRE CONTAS' AS DESCRIPTION,
			'032da0aa-079f-45c6-8340-0171f541644c'::UUID AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::UUID AS SUBCATEGORY_ID,
			AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.TRANSFERS
	),
	TRANSFERS_OUT_INFOS AS (
		SELECT
			SOURCE_ACCOUNT_ID AS ACCOUNT_ID,
			TRANSACTION_DATE,
			'TRANSFERENCIA ENTRE CONTAS' AS DESCRIPTION,
			'032da0aa-079f-45c6-8340-0171f541644c'::UUID AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::UUID AS SUBCATEGORY_ID,
			- AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.TRANSFERS
	),
	CARD_PAYMENTS_INFOS AS (
		SELECT
			ACCOUNT_ID,
			TRANSACTION_DATE,
			'PAGAMENTO CARTÃO | ' || A.BILLING_MONTH AS DESCRIPTION,
			'9e53f2d5-8dbe-4ad0-b0a9-3a81a7a1e0c6'::UUID AS CATEGORY_ID,
			'00000000-0000-0000-0000-000000000000'::UUID AS SUBCATEGORY_ID,
			- AMOUNT,
			DATE_TRUNC('month', TRANSACTION_DATE) AS TIME,
			0 AS IS_LAST_AMOUNT
		FROM
			FINTRACK.CARD_PAYMENTS A
			LEFT JOIN FINTRACK.INVOICES B ON A.CARD_ID = B.CARD_ID AND A.BILLING_MONTH = B.BILLING_MONTH
	),
	UNION_ALL_TRANSACTIONS_INFOS AS (
		SELECT
			*
		FROM
			INCOMES_INFOS
		UNION ALL
		SELECT
			*
		FROM
			INVESTMENT_WITHDRAWAL_INFOS
		UNION ALL
		SELECT
			*
		FROM
			INVESTMENT_DEPOSIT_INFOS
		UNION ALL
		SELECT
			*
		FROM
			EXPENSES_INFOS
		UNION ALL
		SELECT
			*
		FROM
			TRANSFERS_IN_INFOS
		UNION ALL
		SELECT
			*
		FROM
			TRANSFERS_OUT_INFOS
		UNION ALL
		SELECT
			*
		FROM
			CARD_PAYMENTS_INFOS
		UNION ALL
		SELECT
			*
		FROM
			TOTAL_MES_ANTERIOR
	),
	TRANSACTION_WITH_INFOS AS (
		SELECT
			A.TIME,
			A.TRANSACTION_DATE,
			A.DESCRIPTION,
			C.NAME AS CATEGORY,
			D.NAME AS SUBCATEGORY,
			B.NAME AS ACCOUNT,
			A.ACCOUNT_ID,
			AMOUNT,
			A.IS_LAST_AMOUNT
		FROM
			UNION_ALL_TRANSACTIONS_INFOS A
			LEFT JOIN FINTRACK.ACCOUNTS B ON A.ACCOUNT_ID = B.ID
			LEFT JOIN FINTRACK.CATEGORIES C ON A.CATEGORY_ID = C.ID
			LEFT JOIN FINTRACK.SUB_CATEGORIES D ON A.SUBCATEGORY_ID = D.ID
	)
SELECT
	COALESCE(TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD'), '') AS TRANSACTION_DATE,
	COALESCE(DESCRIPTION, '') AS DESCRIPTION,
	COALESCE(AMOUNT, 0) AS AMOUNT,
	COALESCE(CATEGORY, '') AS CATEGORY,
	COALESCE(SUBCATEGORY, '') AS SUBCATEGORY,
	SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID ORDER BY IS_LAST_AMOUNT DESC, TRANSACTION_DATE, AMOUNT DESC) SALDO_DIA
FROM
	TRANSACTION_WITH_INFOS
WHERE
	TIME = TO_DATE('${year}-${month}-01', 'YYYY-MM-DD')
	AND ACCOUNT_ID = ${account}
ORDER BY
			IS_LAST_AMOUNT DESC,  -- Corrigido: DESC para o saldo anterior ficar primeiro
			TRANSACTION_DATE,
			AMOUNT DESC