WITH VALOR_APLICADO AS (
	SELECT
		INVESTMENT_ID,
		MIN(TRANSACTION_DATE) AS FIRST_DEPOSIT,
		SUM(AMOUNT) AMOUNT_DEPOSIT
	FROM FINTRACK.INVESTMENT_DEPOSITS
	GROUP BY INVESTMENT_ID
), VALOR_RESGATADO AS (
	SELECT
		INVESTMENT_ID,
		MAX(TRANSACTION_DATE) AS LAST_WITHDRAWAL,
		SUM(AMOUNT) AMOUNT_WITHDRAWAL
	FROM FINTRACK.INVESTMENT_WITHDRAWALS
	GROUP BY INVESTMENT_ID
)
SELECT
	t1.id,
	T4.NAME AS ACCOUNT_NAME,
	ASSET_NAME,
	IS_RESCUED,
	VALIDITY,
	FIRST_DEPOSIT,
	LAST_WITHDRAWAL,
	AMOUNT_DEPOSIT,
	AMOUNT_WITHDRAWAL,
	AMOUNT_WITHDRAWAL - AMOUNT_DEPOSIT AS RENDIMENTO
FROM FINTRACK.INVESTMENTS T1
LEFT JOIN VALOR_APLICADO T2
ON T1.ID = T2.INVESTMENT_ID
LEFT JOIN VALOR_RESGATADO T3
ON T1.ID = T3.INVESTMENT_ID
LEFT JOIN FINTRACK.ACCOUNTS T4
ON T1.ACCOUNT_ID = T4.ID
ORDER BY FIRST_DEPOSIT
