WITH
	ACCOUNTS AS (
		SELECT
			'201705' AS ANOMES,
			NAME AS ACCOUNT,
			INITIAL_BALANCE AS AMOUNT
		FROM
			PRIVATE.ACCOUNTS
	),
	PAYMENTS_CARD AS (
		SELECT
			TO_CHAR(TRANSACTION_DATE, 'YYYYMM') AS ANOMES,
			T2.NAME AS ACCOUNT,
			SUM(- AMOUNT) AS AMOUNT
		FROM
			PRIVATE.PAYMENT_CARD T1
			INNER JOIN PRIVATE.ACCOUNTS T2 ON T1.ACCOUNT_ID = T2.ID
		GROUP BY
			TO_CHAR(TRANSACTION_DATE, 'YYYYMM'),
			T2.NAME
	),
	EXPENSES AS (
		SELECT
			TO_CHAR(TRANSACTION_DATE, 'YYYYMM') AS ANOMES,
			T2.NAME AS ACCOUNT,
			SUM(- AMOUNT) AS AMOUNT
		FROM
			PRIVATE.EXPENSES T1
			INNER JOIN PRIVATE.ACCOUNTS T2 ON T1.ACCOUNT_ID = T2.ID
		GROUP BY
			TO_CHAR(TRANSACTION_DATE, 'YYYYMM'),
			T2.NAME
	),
	INCOMES AS (
		SELECT
			TO_CHAR(TRANSACTION_DATE, 'YYYYMM') AS ANOMES,
			T2.NAME AS ACCOUNT,
			SUM(AMOUNT) AS AMOUNT
		FROM
			PRIVATE.INCOMES T1
			INNER JOIN PRIVATE.ACCOUNTS T2 ON T1.ACCOUNT_ID = T2.ID
		GROUP BY
			TO_CHAR(TRANSACTION_DATE, 'YYYYMM'),
			T2.NAME
	),
	TRANSFERS AS (
		SELECT
			TO_CHAR(TRANSFER_DATE, 'YYYYMM') AS ANOMES,
			T2.NAME AS ACCOUNT,
			SUM(- AMOUNT) AS AMOUNT
		FROM
			PRIVATE.TRANSFERS T1
			INNER JOIN PRIVATE.ACCOUNTS T2 ON T1.SOURCE_ACCOUNT_ID = T2.ID
		GROUP BY
			TO_CHAR(TRANSFER_DATE, 'YYYYMM'),
			T2.NAME
		UNION ALL
		SELECT
			TO_CHAR(TRANSFER_DATE, 'YYYYMM') AS ANOMES,
			T2.NAME AS ACCOUNT,
			SUM(AMOUNT) AS AMOUNT
		FROM
			PRIVATE.TRANSFERS T1
			INNER JOIN PRIVATE.ACCOUNTS T2 ON T1.DESTINATION_ACCOUNT_ID = T2.ID
		GROUP BY
			TO_CHAR(TRANSFER_DATE, 'YYYYMM'),
			T2.NAME
	),
	ALL_DATA AS (
		SELECT
			ANOMES,
			ACCOUNT,
			AMOUNT
		FROM
			PAYMENTS_CARD
		UNION ALL
		SELECT
			ANOMES,
			ACCOUNT,
			AMOUNT
		FROM
			EXPENSES
		UNION ALL
		SELECT
			ANOMES,
			ACCOUNT,
			AMOUNT
		FROM
			INCOMES
		UNION ALL
		SELECT
			ANOMES,
			ACCOUNT,
			AMOUNT
		FROM
			TRANSFERS
		UNION ALL
		SELECT
			ANOMES,
			ACCOUNT,
			AMOUNT
		FROM
			ACCOUNTS
	),
	RESUME AS (
		SELECT
			ACCOUNT,
			SUM(AMOUNT) AS AMOUNT
		FROM
			ALL_DATA
		GROUP BY
			ACCOUNT
	)
SELECT
	*
FROM
	RESUME