Table users {
    id UUID [primary key, default: `uuid_generate_v4()`]
    name VARCHAR(100) [not null]
    username VARCHAR(100) [not null, unique]
    email VARCHAR(100) [not null, unique]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table accounts {
    id UUID [primary key, default: `uuid_generate_v4()`]
    user_id UUID [not null, ref: >  users.id]
    name VARCHAR(100) [not null, unique]
    type VARCHAR(50) [not null]
    initial_balance NUMERIC(15, 2) [not null]
    currency VARCHAR(10) [not null]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table categories {
    id UUID [primary key, default: `uuid_generate_v4()`]
    name VARCHAR(100) [not null, unique]
    color VARCHAR(100) [not null]
    icon VARCHAR(100) [not null]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table subcategories {
    id UUID [primary key, default: `uuid_generate_v4()`]
    name VARCHAR(100) [not null, unique]
    category_id UUID [not null, ref: > categories.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table transaction_statuses {
    id UUID [primary key, default: `uuid_generate_v4()`]
    name VARCHAR(50) [not null, unique]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table cards {
    id UUID [primary key, default: `uuid_generate_v4()`]
    name VARCHAR(100) [not null, unique]
    credit_limit NUMERIC(15, 2) [not null]
    account_id UUID [not null, ref: > accounts.id]
    closing_date INTEGER [not null]
    due_date INTEGER [not null]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table invoices {
    id UUID [primary key, default: `uuid_generate_v4()`]
    card_id UUID [not null, ref: > cards.id]
    billing_month DATE [not null]
    status UUID [not null, ref: > transaction_statuses.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
    indexes {
    (card_id, billing_month) [unique]
  }
  }
  
  Table transfers {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transfer_date DATE [not null]
    amount NUMERIC(15, 2) [not null]
    source_account_id UUID [not null, ref: > accounts.id]
    destination_account_id UUID [not null, ref: > accounts.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table recurring_transactions {
    id UUID [primary key, default: `uuid_generate_v4()`]
    amount NUMERIC(15, 2) [not null]
    description VARCHAR(50) [not null]
    frequency VARCHAR(50) [not null]
    start_date DATE [not null]
    end_date DATE
    account_id UUID [not null, ref: > accounts.id]
    category_id UUID [not null, ref: > categories.id]
    subcategory_id UUID [ref: > subcategories.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table investments {
    id UUID [primary key, default: `uuid_generate_v4()`]
    asset_name VARCHAR(100) [not null]
    type VARCHAR(50) [not null]
    account_id UUID [not null, ref: > accounts.id]
    index_type VARCHAR(50)
    index_value VARCHAR(50)
    liquidity VARCHAR(50)
    fl_rescued BOOLEAN
    validity DATE
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table tags {
    id UUID [primary key, default: `uuid_generate_v4()`]
    name VARCHAR(100) [not null]
    color VARCHAR(20)
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table recurring_transactions_tags {
    recurring_transactions_id UUID [not null, ref: > recurring_transactions.id]
    tag_id UUID [not null, ref: > tags.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table incomes {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    description TEXT
    amount NUMERIC(15, 2) [not null]
    account_id UUID [not null, ref: > accounts.id]
    recurring_transaction_id UUID [ref: > recurring_transactions.id]
    category_id UUID [not null, ref: > categories.id]
    subcategory_id UUID [ref: > subcategories.id]
    transaction_status_id UUID [not null, ref: > transaction_statuses.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table expenses {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    description TEXT
    amount NUMERIC(15, 2) [not null]
    account_id UUID [not null, ref: > accounts.id]
    category_id UUID [not null, ref: > categories.id]
    subcategory_id UUID [ref: > subcategories.id]
    transaction_status_id UUID [not null, ref: > transaction_statuses.id]
    recurring_transaction_id UUID [ref: > recurring_transactions.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table expenses_card {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    description TEXT
    amount NUMERIC(15, 2) [not null]
    subcategory_id UUID [ref: > subcategories.id]
    category_id UUID [ref: > categories.id]
    recurring_transaction_id UUID [ref: > recurring_transactions.id]
    invoice_id UUID [ref: > invoices.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table chargeback_card {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    description TEXT
    amount NUMERIC(15, 2) [not null]
    invoice_id UUID [ref: > invoices.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table payment_card {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    amount NUMERIC(15, 2) [not null]
    account_id UUID [not null, ref: > accounts.id]
    invoice_id UUID [not null, ref: > invoices.id]
    fl_finally BOOLEAN [not null, default: false]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table investment_deposit {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    description TEXT
    amount NUMERIC(15, 2) [not null]
    recurring_transaction_id UUID [ref: > recurring_transactions.id]
    investment_id UUID [ref: > investments.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table investment_withdrawal {
    id UUID [primary key, default: `uuid_generate_v4()`]
    transaction_date DATE [not null]
    description TEXT
    amount NUMERIC(15, 2) [not null]
    recurring_transaction_id UUID [ref: > recurring_transactions.id]
    investment_id UUID [ref: > investments.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table incomes_tags {
    income_id UUID [not null, ref: > incomes.id]
    tag_id UUID [not null, ref: > tags.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table expenses_tags {
    expense_id UUID [not null, ref: > expenses.id]
    tag_id UUID [not null, ref: > tags.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table investments_tags {
    investment_id UUID [not null, ref: > investments.id]
    tag_id UUID [not null, ref: > tags.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
  
  Table expense_card_tags {
    expense_card_id UUID [not null, ref: > expenses_card.id]
    tag_id UUID [not null, ref: > tags.id]
    created_at TIMESTAMP [default: `now()`]
    updated_at TIMESTAMP [default: `now()`]
  }
