FROM mcr.microsoft.com/vscode/devcontainers/go:latest

RUN git config user.name phraulino
RUN git config user.email phraulino@outlook.com

# use this Dockerfile to install additional tools you might need, e.g.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
